"""Static demo data. Every record created from this file is stored with is_demo=True."""

# ~85% Indian names across regions, ~15% international.
INDIAN_FIRST_M = ["Aarav", "Vihaan", "Arjun", "Rohan", "Kabir", "Ishaan", "Aditya", "Siddharth", "Karthik", "Pranav",
                  "Rahul", "Nikhil", "Varun", "Aniket", "Harsh", "Yash", "Dhruv", "Manav", "Rishi", "Omkar",
                  "Sameer", "Tanmay", "Abhishek", "Vivek", "Gaurav", "Arnav", "Shreyas", "Kunal", "Naveen", "Suresh",
                  "Farhan", "Imran", "Gurpreet", "Harjot", "Anirban", "Sourav", "Vignesh", "Pradeep", "Akhil", "Joel"]
INDIAN_FIRST_F = ["Ananya", "Diya", "Saanvi", "Aditi", "Priya", "Kavya", "Isha", "Meera", "Riya", "Neha",
                  "Pooja", "Sneha", "Tanvi", "Shruti", "Nandini", "Ira", "Myra", "Anika", "Lavanya", "Divya",
                  "Aishwarya", "Swati", "Pallavi", "Radhika", "Zoya", "Sana", "Simran", "Harleen", "Moumita", "Sreeja",
                  "Keerthana", "Deepika", "Nisha", "Mrinalini", "Gayatri", "Ritika", "Trisha", "Anjali", "Mehak", "Fatima"]
INDIAN_LAST = ["Sharma", "Verma", "Mehta", "Patel", "Shah", "Iyer", "Nair", "Menon", "Reddy", "Rao",
               "Kulkarni", "Deshpande", "Joshi", "Gupta", "Agarwal", "Bansal", "Malhotra", "Kapoor", "Chopra", "Singh",
               "Sandhu", "Gill", "Das", "Banerjee", "Mukherjee", "Chatterjee", "Bose", "Sen", "Pillai", "Krishnan",
               "Subramanian", "Naidu", "Choudhury", "Khan", "Qureshi", "Siddiqui", "D'Souza", "Fernandes", "Pereira", "Jain",
               "Thakur", "Saxena", "Mishra", "Tiwari", "Pandey", "Bhat", "Hegde", "Shetty", "Kamath", "Dutta"]
INDIAN_CITIES = [("Bengaluru", "Karnataka"), ("Mumbai", "Maharashtra"), ("Pune", "Maharashtra"), ("Delhi", "Delhi"),
                 ("Gurugram", "Haryana"), ("Noida", "Uttar Pradesh"), ("Hyderabad", "Telangana"),
                 ("Chennai", "Tamil Nadu"), ("Kolkata", "West Bengal"), ("Ahmedabad", "Gujarat"),
                 ("Jaipur", "Rajasthan"), ("Kochi", "Kerala"), ("Chandigarh", "Chandigarh"), ("Indore", "Madhya Pradesh"),
                 ("Lucknow", "Uttar Pradesh"), ("Coimbatore", "Tamil Nadu"), ("Goa", "Goa"), ("Bhubaneswar", "Odisha")]

INTERNATIONAL = [
    ("Liam", "Carter", "London", "United Kingdom"), ("Sofia", "Rossi", "Milan", "Italy"),
    ("Lucas", "Moreau", "Lyon", "France"), ("Emma", "Schneider", "Berlin", "Germany"),
    ("Mateo", "García", "Madrid", "Spain"), ("Hana", "Takahashi", "Tokyo", "Japan"),
    ("Min-jun", "Park", "Seoul", "South Korea"), ("Chloe", "Nguyen", "Melbourne", "Australia"),
    ("Daniel", "Okafor", "Lagos", "Nigeria"), ("Amelia", "Brooks", "Toronto", "Canada"),
    ("Noah", "Jensen", "Copenhagen", "Denmark"), ("Layla", "Haddad", "Dubai", "United Arab Emirates"),
    ("Ethan", "Walker", "Austin", "United States"), ("Isabela", "Costa", "São Paulo", "Brazil"),
    ("Wei", "Lim", "Singapore", "Singapore"), ("Sven", "Lindqvist", "Stockholm", "Sweden"),
    ("Ayesha", "Rahman", "Dhaka", "Bangladesh"), ("Nimal", "Perera", "Colombo", "Sri Lanka"),
    ("Olivia", "Hughes", "Dublin", "Ireland"), ("Jonas", "de Vries", "Amsterdam", "Netherlands"),
]

CREATOR_ROLES = {
    "3D & design": ["3D designer", "Product visualiser", "Material artist", "Brand designer", "Illustrator"],
    "AI workflows": ["Workflow creator", "Automation engineer", "Prompt designer", "Growth marketer", "Data analyst"],
    "Motion & video": ["Motion artist", "Video editor", "Colourist", "Title designer", "Animator"],
}
MEMBER_ROLES = ["Founder", "Freelance designer", "Content creator", "Marketing lead", "Studio owner", "Student",
                "Product designer", "Agency producer", "YouTuber", "Indie developer", "Photographer", "Brand strategist"]

TRANSFER_MEMOS = ["Thanks for the files!", "Collab split", "For the logo revisions", "Your share from the client project",
                  "Tip for the tutorial 🙏", "Reimbursing the pass", "Payment for the edit", "Group buy share",
                  "Thanks for the feedback session", "For the thumbnail pack", "Splitting the studio licence",
                  "Bonus for fast turnaround", None, None, None]

# (name, category, kind, base_price, format, description, includes)
ASSETS = [
    # --- the three launch assets already on the site (keep ids so frontend links still work) ---
    ("Prism Material Kit", "3D & design", "file", 499, "BLEND · 24 materials",
     "Glass, liquid chrome, and soft metallic materials for product renders and expressive 3D compositions.",
     ["24 material presets", "Blender scene with studio lighting", "Setup guide and license receipt"]),
    ("Brand-to-Content Engine", "AI workflows", "hosted", 899, "HOSTED · 50 runs / 7 days",
     "Turns a brand brief into a structured content plan, draft captions, and a review checklist.",
     ["Brand brief → content plan pipeline", "Editable tone and channel settings", "50 runs in a 7-day pass"]),
    ("Fluid Motion Vol. 01", "Motion & video", "file", 699, "MOV · 12 seamless loops",
     "Cinematic cobalt motion loops for title sequences, background visuals, and launch films.",
     ["12 4K seamless loops", "Landscape and portrait crops", "Colour adjustment notes"]),
    # --- 3D & design ---
    ("Diwali Festive Mockup Pack", "3D & design", "file", 399, "PSD · 18 mockups",
     "Diya, rangoli and gift-box scenes ready for festive product launches and social posts.",
     ["18 layered PSD mockups", "Smart-object labels", "Warm and neutral lighting variants"]),
    ("Clay Character Starter", "3D & design", "file", 799, "BLEND · 6 rigs",
     "Soft clay-style characters with simple rigs for explainer videos and app onboarding.",
     ["6 rigged characters", "Pose library", "Toon shader setup"]),
    ("Indian Textile Patterns", "3D & design", "file", 299, "SVG + PNG · 60 tiles",
     "Seamless vector patterns inspired by Ajrakh, Bandhani and Ikat for packaging and apparel.",
     ["60 seamless tiles", "Editable SVG sources", "Colourway guide"]),
    ("Isometric Office Kit", "3D & design", "file", 549, "FIG + GLB · 120 objects",
     "Isometric desks, plants and devices for SaaS landing pages and pitch decks.",
     ["120 isometric objects", "Figma component library", "GLB exports"]),
    ("Chrome Type Studio", "3D & design", "file", 649, "BLEND · 40 letterforms",
     "Inflated chrome 3D letters and numerals for posters, covers and album art.",
     ["A–Z and 0–9 in chrome", "HDRI lighting presets", "Render-ready scene"]),
    ("Packaging Dieline Library", "3D & design", "file", 449, "AI + PDF · 35 dielines",
     "Print-ready dielines for boxes, sleeves and pouches common with Indian D2C brands.",
     ["35 print-ready dielines", "Bleed and fold guides", "3D preview mockups"]),
    ("Minimal Icon Set — Fintech", "3D & design", "file", 249, "SVG · 320 icons",
     "Clean line icons for UPI, wallets, cards and investments with consistent 1.5px strokes.",
     ["320 SVG icons", "Figma variants", "React-ready export"]),
    ("Studio Product Lighting HDRIs", "3D & design", "file", 599, "EXR · 16 HDRIs",
     "Softbox and rim-light HDRIs for crisp e-commerce renders.",
     ["16 high-res HDRIs", "Blender and C4D presets", "Reference renders"]),
    ("Wedding Invite Templates", "3D & design", "file", 349, "PSD + CANVA · 12 suites",
     "Modern invite suites with Hindi, Tamil and English typography options.",
     ["12 invitation suites", "RSVP and menu cards", "Font pairing notes"]),
    ("Low-Poly City Blocks", "3D & design", "file", 699, "FBX · 48 buildings",
     "Game-ready low-poly buildings, roads and props for stylised city scenes.",
     ["48 modular buildings", "Road tile system", "Unity and Unreal ready"]),
    ("Gradient Mesh Backgrounds", "3D & design", "file", 199, "PNG + FIG · 80 gradients",
     "High-resolution mesh gradients for app screens, slides and social banners.",
     ["80 gradients up to 8K", "Figma source", "Dark and light sets"]),
    ("Holi Colour Splash Brushes", "3D & design", "file", 249, "ABR · 45 brushes",
     "Powder-burst and splash brushes captured from real colour-throw photography.",
     ["45 Photoshop brushes", "Procreate version", "Sample artwork"]),
    # --- AI workflows ---
    ("GST Invoice Parser", "AI workflows", "hosted", 699, "HOSTED · 100 runs / 7 days",
     "Extracts GSTIN, HSN codes, taxes and totals from invoice PDFs into a clean spreadsheet.",
     ["PDF and image input", "CSV and Sheets export", "Validation report"]),
    ("YouTube Shorts Repurposer", "AI workflows", "hosted", 599, "HOSTED · 40 runs / 7 days",
     "Finds the strongest moments in long videos and drafts hooks, captions and titles for Shorts.",
     ["Moment detection", "Hook and caption drafts", "Hindi and English output"]),
    ("Real-Estate Listing Writer", "AI workflows", "hosted", 499, "HOSTED · 60 runs / 7 days",
     "Turns property details and photos into listing copy for portals, WhatsApp and Instagram.",
     ["Portal-ready descriptions", "WhatsApp broadcast version", "Tone presets"]),
    ("Customer Support Triage Bot", "AI workflows", "hosted", 1099, "HOSTED · 500 tickets / 7 days",
     "Classifies support emails by intent and urgency and drafts first replies for review.",
     ["Intent and urgency tags", "Draft replies", "Weekly summary"]),
    ("Resume-to-Portfolio Builder", "AI workflows", "hosted", 399, "HOSTED · 20 runs / 7 days",
     "Converts a resume into a structured personal portfolio page with project write-ups.",
     ["Portfolio page draft", "Project case-study outlines", "SEO title and bio"]),
    ("Instagram Carousel Generator", "AI workflows", "hosted", 699, "HOSTED · 50 runs / 7 days",
     "Builds slide-by-slide carousel copy and layout suggestions from a single topic.",
     ["10-slide structures", "Caption and hashtags", "Brand colour presets"]),
    ("Meeting Notes to Action Items", "AI workflows", "hosted", 449, "HOSTED · 80 runs / 7 days",
     "Summarises call transcripts into decisions, owners and deadlines.",
     ["Decision log", "Owner and due-date table", "Slack-ready summary"]),
    ("D2C Product Description Pack", "AI workflows", "hosted", 799, "HOSTED · 150 SKUs / 7 days",
     "Writes consistent product titles, bullets and descriptions for Shopify and marketplaces.",
     ["Title and bullet templates", "Marketplace character limits", "Bulk CSV upload"]),
    ("Podcast Show-Notes Engine", "AI workflows", "hosted", 549, "HOSTED · 30 episodes / 7 days",
     "Generates timestamps, show notes and social snippets from podcast audio.",
     ["Chapter timestamps", "Show notes", "Quote cards text"]),
    ("Cold Email Personaliser", "AI workflows", "hosted", 899, "HOSTED · 300 leads / 7 days",
     "Researches public company info and drafts personalised first lines for outreach.",
     ["Lead enrichment", "First-line drafts", "Sequence templates"]),
    ("Exam Question Bank Builder", "AI workflows", "hosted", 349, "HOSTED · 40 runs / 7 days",
     "Creates MCQs and short-answer questions from chapter notes with answer keys.",
     ["MCQ and short-answer sets", "Difficulty levels", "Answer keys"]),
    # --- Motion & video ---
    ("Bollywood Title Pack", "Motion & video", "file", 899, "AEP + MOGRT · 30 titles",
     "Dramatic, glitter and retro title animations inspired by Hindi film posters.",
     ["30 animated titles", "Premiere MOGRTs", "Font suggestions"]),
    ("Monsoon Cinematic LUTs", "Motion & video", "file", 449, "CUBE · 25 LUTs",
     "Moody teal-grey grades built for rainy exteriors and street footage.",
     ["25 .cube LUTs", "Log and Rec.709 versions", "Before/after guide"]),
    ("Kinetic Typography Toolkit", "Motion & video", "file", 999, "AEP · 60 scenes",
     "Fast kinetic type scenes for reels, ads and product launches.",
     ["60 editable scenes", "Auto-resize for 9:16 and 16:9", "Tutorial video"]),
    ("Wedding Film Transitions", "Motion & video", "file", 599, "PRPROJ · 80 transitions",
     "Light leaks, petals and film-burn transitions tuned for wedding edits.",
     ["80 drag-and-drop transitions", "Sound effects", "4K ready"]),
    ("Lo-fi Loop Backgrounds", "Motion & video", "file", 349, "MP4 · 20 loops",
     "Calm animated backgrounds for study streams, podcasts and ambient videos.",
     ["20 seamless loops", "Day and night versions", "1080p and 4K"]),
    ("Explainer Icon Animations", "Motion & video", "file", 499, "LOTTIE · 150 icons",
     "Lightweight Lottie icon animations for apps, websites and explainers.",
     ["150 Lottie JSON files", "After Effects sources", "Colour-swap guide"]),
    ("Cricket Broadcast Graphics", "Motion & video", "file", 1199, "AEP · 40 elements",
     "Scorebugs, lower thirds and player cards for local league streams.",
     ["40 broadcast elements", "OBS-friendly exports", "Team colour controls"]),
    ("Glitch & Distortion FX", "Motion & video", "file", 399, "MOV · 70 overlays",
     "Digital glitch, VHS and datamosh overlays with alpha channels.",
     ["70 alpha overlays", "Sound design pack", "Preset blend modes"]),
    ("Product Reveal Templates", "Motion & video", "file", 749, "AEP · 12 reveals",
     "Premium product reveal animations for launches and e-commerce ads.",
     ["12 reveal templates", "Drop-in product placeholders", "Music suggestions"]),
    ("Travel Vlog Colour Kit", "Motion & video", "file", 399, "CUBE + DRX · 18 grades",
     "Warm, filmic grades for travel footage from Ladakh beaches to Kerala backwaters.",
     ["18 LUTs", "DaVinci Resolve power grades", "Shooting tips"]),
]
