export type LicenseOption={id:string;name:string;detail:string;price:number};
export type Asset={id:string;name:string;category:string;creator:string;creator_handle?:string;initials:string;role:string;price:number;image:string;format:string;description:string;includes:string[];kind:'file'|'hosted';tag:string;is_demo?:boolean;stats?:{sales:number;revenue:number};license_options?:LicenseOption[]};
// Fallback catalogue, used only when the API is unreachable.
export const assets:Asset[]=[
{id:'prism',name:'Prism Material Kit',category:'3D & design',creator:'Aarav Mehta',initials:'AM',role:'3D designer',price:499,image:'/art/prism.webp',format:'BLEND · 24 materials',description:'Glass, liquid chrome, and soft metallic materials for product renders and expressive 3D compositions.',includes:['24 material presets','Blender scene with studio lighting','Setup guide and license receipt'],kind:'file',tag:'THE MATERIAL EDIT'},
{id:'flowstate',name:'Brand-to-Content Engine',category:'AI workflows',creator:'Mira Sen',initials:'MS',role:'Workflow creator',price:899,image:'/art/flowstate.webp',format:'HOSTED · 50 runs / 7 days',description:'Turns a brand brief into a structured content plan, draft captions, and a review checklist.',includes:['Brand brief → content plan pipeline','Editable tone and channel settings','50 runs in a 7-day pass'],kind:'hosted',tag:'THE WORKFLOW EDIT'},
{id:'fluid',name:'Fluid Motion Vol. 01',category:'Motion & video',creator:'Rohan Das',initials:'RD',role:'Motion artist',price:699,image:'/art/fluid.webp',format:'MOV · 12 seamless loops',description:'Cinematic cobalt motion loops for title sequences, background visuals, and launch films.',includes:['12 4K seamless loops','Landscape and portrait crops','Colour adjustment notes'],kind:'file',tag:'THE MOTION EDIT'}];
export const categories=['All assets','3D & design','AI workflows','Motion & video'];
export function money(v:number){return new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(v)+' credits'}
export function licenseOptions(asset:Asset):LicenseOption[]{if(asset.license_options?.length)return asset.license_options;return asset.kind==='hosted'?[{id:'week',name:'7-day pass',detail:'50 runs · one user',price:asset.price},{id:'month',name:'30-day pass',detail:'250 runs · one user',price:asset.price*3}]:[{id:'personal',name:'Personal',detail:'One user · non-commercial projects',price:asset.price},{id:'commercial',name:'Commercial',detail:'One user · client and commercial work',price:asset.price*2},{id:'studio',name:'Studio',detail:'Up to 5 users · commercial work',price:asset.price*4}];}
export function timeAgo(iso:string){const s=Math.max(1,Math.round((Date.now()-new Date(iso).getTime())/1000));if(s<60)return 'just now';const m=Math.round(s/60);if(m<60)return m+'m ago';const h=Math.round(m/60);if(h<24)return h+'h ago';return Math.round(h/24)+'d ago'}
