'use client';
import { useEffect,useRef,useState } from 'react';
import { Pause, Play, RotateCcw, Move } from 'lucide-react';
export default function Orbit(){
 const mount=useRef<HTMLDivElement>(null);const playing=useRef(true);const reset=useRef<()=>void>(()=>{});const [paused,setPaused]=useState(false);const [ready,setReady]=useState(false);
 useEffect(()=>{let cleanup=()=>{};let cancelled=false;
  (async()=>{try{
   const THREE=await import('three');const {RoomEnvironment}=await import('three/addons/environments/RoomEnvironment.js');
   if(cancelled||!mount.current)return;
   const root=mount.current;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(0,0,8.4);
   const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.7));renderer.setClearColor(0x080a0e,0);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.65;root.appendChild(renderer.domElement);
   const pmrem=new THREE.PMREMGenerator(renderer);const room=new RoomEnvironment();const environment=pmrem.fromScene(room,.04);scene.environment=environment.texture;room.dispose();pmrem.dispose();
   const group=new THREE.Group();scene.add(group);const geo=new THREE.TorusKnotGeometry(1.07,.32,200,32,2,3);const mat=new THREE.MeshPhysicalMaterial({color:0x91b4e3,metalness:.86,roughness:.12,clearcoat:1,clearcoatRoughness:.08,iridescence:.35,iridescenceIOR:1.4});const knot=new THREE.Mesh(geo,mat);group.add(knot);
   const ringGeo=new THREE.TorusGeometry(1.82,.021,12,128);const ringMat=new THREE.MeshStandardMaterial({color:0xa2c5ed,metalness:.75,roughness:.3});const ring=new THREE.Mesh(ringGeo,ringMat);ring.rotation.set(.9,-.3,.3);group.add(ring);
   const beadGeo=new THREE.SphereGeometry(.12,24,24);const beadMat=new THREE.MeshPhysicalMaterial({color:0xdbff8b,metalness:.55,roughness:.17,clearcoat:1});const beads:Array<InstanceType<typeof THREE.Mesh>>=[];for(let i=0;i<3;i++){const bead=new THREE.Mesh(beadGeo,i===1?mat:beadMat);beads.push(bead);scene.add(bead)}
   const light=new THREE.DirectionalLight(0xc3e1ff,3);light.position.set(2,3,3);scene.add(light);const rim=new THREE.PointLight(0x79a8ff,15);rim.position.set(-3,-1,2);scene.add(rim);scene.add(new THREE.AmbientLight(0xffffff,.5));
   group.rotation.set(.3,.4,-.25);let mx=0,my=0,drag=false,prevX=0,prevY=0,t=0,last=0,frame=0,visible=true;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');playing.current=!reduced.matches;setPaused(reduced.matches);
   const resize=()=>{const w=root.clientWidth,h=root.clientHeight;if(w&&h){camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)}};const ro=new ResizeObserver(resize);ro.observe(root);resize();
   const move=(e:PointerEvent)=>{const r=root.getBoundingClientRect();mx=(e.clientX-r.left)/r.width-.5;my=(e.clientY-r.top)/r.height-.5;if(drag){group.rotation.y+=(e.clientX-prevX)*.009;group.rotation.x+=(e.clientY-prevY)*.009}prevX=e.clientX;prevY=e.clientY};const down=(e:PointerEvent)=>{drag=true;prevX=e.clientX;prevY=e.clientY;root.setPointerCapture(e.pointerId)};const up=()=>{drag=false};root.addEventListener('pointermove',move);root.addEventListener('pointerdown',down);root.addEventListener('pointerup',up);root.addEventListener('pointercancel',up);
   const io=new IntersectionObserver(e=>{visible=e[0].isIntersecting});io.observe(root);const lost=(e:Event)=>{e.preventDefault();setReady(false)};renderer.domElement.addEventListener('webglcontextlost',lost);reset.current=()=>{group.rotation.set(.3,.4,-.25);mx=0;my=0};
   const render=(now:number)=>{frame=requestAnimationFrame(render);if(!visible||document.hidden||now-last<30)return;const dt=Math.min((now-last)/1000,.05);last=now;if(playing.current&&!drag){t+=dt;group.rotation.y+=dt*.13;knot.rotation.z=Math.sin(t*.35)*.1;group.position.y=Math.sin(t*.7)*.07;group.rotation.x+=(.3+my*.25-group.rotation.x)*.02;group.rotation.z+=(-.25+mx*.12-group.rotation.z)*.02}beads.forEach((b,i)=>{const a=t*.22+i*2.1;b.position.set(Math.cos(a)*2.05,Math.sin(a)*1.32,Math.sin(a)*.6);b.scale.setScalar(i===2?.65:1)});renderer.render(scene,camera)};render(32);setReady(true);
   cleanup=()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();root.removeEventListener('pointermove',move);root.removeEventListener('pointerdown',down);root.removeEventListener('pointerup',up);root.removeEventListener('pointercancel',up);renderer.domElement.removeEventListener('webglcontextlost',lost);geo.dispose();mat.dispose();ringGeo.dispose();ringMat.dispose();beadGeo.dispose();beadMat.dispose();environment.dispose();renderer.dispose();renderer.domElement.remove()};
  }catch{setReady(false)}})();return()=>{cancelled=true;cleanup()};
 },[]);
 return <div className="orbit"><img className={'orbit-fallback '+(ready?'hidden-fallback':'')} src="/art/prism.png" alt="Interconnected glass and chrome forms"/><div ref={mount} className="orbit-canvas" aria-label="Rotating 3D sculpture. Drag to rotate." role="img"/><span className="orbit-caption"><Move size={13}/>{ready?'DRAG TO EXPLORE':'CREATIVE CONNECTIONS'}</span>{ready&&<div className="orbit-controls"><button onClick={()=>{playing.current=!playing.current;setPaused(!playing.current)}} aria-label={paused?'Play 3D animation':'Pause 3D animation'}>{paused?<Play size={15}/>:<Pause size={15}/>}</button><button aria-label="Reset 3D view" onClick={()=>reset.current()}><RotateCcw size={15}/></button></div>}</div>
}
