'use client';
import { useState, useEffect } from 'react';
import { flushSync } from 'react-dom';
import { ArrowUpRight, Search, Plus, Box, Workflow, Film, Bookmark, ArrowRight, Link2, Check, ShieldCheck, FileText, X, CheckCircle2, LayoutGrid, PackageOpen, Clock, Sparkles } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Sheet,SheetContent,SheetTitle,SheetDescription } from '@/components/ui/sheet';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { RadioGroup,RadioGroupItem } from '@/components/ui/radio-group';
import { Checkbox } from '@/components/ui/checkbox';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import Orbit from './orbit';
import { assets,categories,money,licenseOptions,type Asset } from './market-data';
type Receipt={id:string;asset:Asset;license:string;price:number;created:string};
type Draft={id:string;name:string;category:string;description:string;price:number};
export default function Home(){
 const [category,setCategory]=useState('All assets');const [query,setQuery]=useState('');const [saved,setSaved]=useState<string[]>([]);const [asset,setAsset]=useState<Asset|null>(null);const [option,setOption]=useState('personal');const [accepted,setAccepted]=useState(false);const [receipt,setReceipt]=useState<Receipt|null>(null);const [receipts,setReceipts]=useState<Receipt[]>([]);const [collection,setCollection]=useState(false);const [listing,setListing]=useState(false);const [drafts,setDrafts]=useState<Draft[]>([]);const [draftCategory,setDraftCategory]=useState('3D & design');const [rights,setRights]=useState(false);const [draftCreated,setDraftCreated]=useState(false);
 const filtered=assets.filter(a=>(category==='All assets'||a.category===category)&&`${a.name} ${a.category} ${a.creator} ${a.description}`.toLowerCase().includes(query.toLowerCase().trim()));
 const openAsset=(a:Asset)=>{setAsset(a);setOption(licenseOptions(a)[0].id);setAccepted(false);setReceipt(null)};
 const toggleSaved=(id:string)=>setSaved(s=>s.includes(id)?s.filter(v=>v!==id):[...s,id]);
 const selection=asset?licenseOptions(asset).find(x=>x.id===option)??licenseOptions(asset)[0]:null;
 const simulate=()=>{if(!asset||!selection||!accepted)return;const r={id:'DEMO-'+crypto.randomUUID().slice(0,8).toUpperCase(),asset,license:selection.name,price:selection.price,created:new Date().toISOString()};setReceipt(r);setReceipts(prev=>[r,...prev])};
 useEffect(()=>{
  const context=(document as unknown as {modelContext?:{registerTool:(tool:Record<string,unknown>,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();
  const register=(tool:Record<string,unknown>)=>{try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{})}catch{}};
  register({name:'search_smartsharing_assets',title:'Search SmartSharing assets',description:'Filter the visible concept marketplace. All listings and prices are illustrative.',inputSchema:{type:'object',properties:{query:{type:'string'},category:{type:'string',enum:categories}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object')throw Error('Expected an object');const v=input as Record<string,unknown>;if(v.query!==undefined&&typeof v.query!=='string')throw Error('query must be text');if(v.category!==undefined&&!categories.includes(v.category as string))throw Error('Invalid category');const q=(v.query as string)||'',c=(v.category as string)||'All assets';flushSync(()=>{setQuery(q);setCategory(c)});document.getElementById('explore')?.scrollIntoView();return{assets:assets.filter(a=>(c==='All assets'||a.category===c)&&`${a.name} ${a.category} ${a.creator} ${a.description}`.toLowerCase().includes(q.toLowerCase().trim())).map(a=>({id:a.id,name:a.name,startingPriceINR:a.price})),mode:'demo'}}});
  register({name:'open_smartsharing_asset',title:'Preview an asset',description:'Open the visible asset detail and demo license selector. Does not purchase anything.',inputSchema:{type:'object',properties:{assetId:{type:'string',enum:assets.map(a=>a.id)}},required:['assetId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const id=(input as {assetId?:unknown})?.assetId;const a=assets.find(x=>x.id===id);if(!a)throw Error('Unknown asset ID');flushSync(()=>openAsset(a));return{opened:a.id,mode:'demo',paymentTaken:false}}});
  return()=>life.abort();
 },[]);
 return <>
 <header className="site-header"><a href="/" className="brand" aria-label="SmartSharing home"><Link2/>smartsharing<span>.in</span></a><nav aria-label="Main navigation"><a className="active" href="/">Discover</a><a href="#how-it-works">How it works</a><a href="/research">The research <ArrowUpRight size={14}/></a></nav><button className="button quiet" onClick={()=>setCollection(true)} aria-label="Open my collection"><Bookmark size={17}/> My collection{saved.length+receipts.length+drafts.length>0&&<span className="count">{saved.length+receipts.length+drafts.length}</span>}</button><button className="button primary" onClick={()=>{setListing(true);setDraftCreated(false)}}><Plus size={17}/> List an asset</button></header>
 <main className="market">
 <section className="hero"><div className="hero-copy"><p className="eyebrow">THE CREATOR-TO-CREATOR EXCHANGE</p><h1>Great work.<br/>Made to <span>go further.</span></h1><p>Discover digital assets and AI workflows.<br/>License directly from the people who make them.</p><a className="button primary" href="#explore">Find your next asset <ArrowUpRight size={18}/></a><a className="hero-secondary" href="/research">Explore the idea <ArrowRight size={15}/></a></div><div className="hero-object"><Orbit/><button className="featured-label" onClick={()=>openAsset(assets[0])}><span className="featured-square"><Box size={18}/></span><span><small>IN THE SPOTLIGHT</small><strong>Prism Material Kit</strong></span><ArrowUpRight size={18}/></button></div><div className="hero-bottom"><span>Created by people. Shared with purpose.</span><span>Clear licenses <b>•</b> Creator-first economics</span></div></section>
 <section id="explore" aria-labelledby="explore-title"><div className="section-heading"><h2 id="explore-title">Find your next building block<span>.</span></h2><span>THE FIRST COLLECTION / 001</span></div><div className="market-tools"><div className="categories" aria-label="Filter by category">{categories.map((x,i)=>{const Icon=[LayoutGrid,Box,Workflow,Film][i];return <button key={x} aria-pressed={category===x} className={category===x?'selected':''} onClick={()=>setCategory(x)}><Icon size={15}/>{x}</button>})}</div><div className="search-field"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search assets or creators" aria-label="Search assets or creators"/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={15}/></button>}</div></div>
 <div className="catalog-meta"><span aria-live="polite">{filtered.length} {filtered.length===1?'asset':'assets'} to explore</span><span className="concept-badge">CONCEPT COLLECTION</span></div>
 <div className="asset-grid">{filtered.map((a,i)=><article className="asset-card" key={a.id}><div className="asset-art"><button className="art-button" onClick={()=>openAsset(a)} aria-label={'Explore '+a.name}><img src={a.image} alt={a.id==='prism'?'Ice-blue glass and chrome interlocking forms':a.id==='flowstate'?'Chartreuse glass blocks arranged as a workflow sculpture':'Cobalt liquid waves with fine contour lines'} width={768} height={512}/><span className="art-edit">{a.tag}</span><span className="art-open"><ArrowUpRight size={22}/></span></button><button className={'save-asset '+(saved.includes(a.id)?'is-saved':'')} onClick={()=>toggleSaved(a.id)} aria-label={(saved.includes(a.id)?'Unsave ':'Save ')+a.name} aria-pressed={saved.includes(a.id)}><Bookmark size={17} fill={saved.includes(a.id)?'currentColor':'none'}/></button></div><div className="asset-info"><div className="asset-type"><p className="asset-category">{a.category}</p><span>{a.kind==='hosted'?'ACCESS PASS':'LICENSE'}</span></div><h3><button onClick={()=>openAsset(a)}>{a.name}</button></h3><div className="creator-line"><span className={'avatar avatar-'+a.id}>{a.initials}</span><span>{a.creator}<small>{a.role}</small></span></div><div className="asset-bottom"><span><small>From </small>{money(a.price)}<small>{a.kind==='hosted'?' / 7 days':''}</small></span><button onClick={()=>openAsset(a)} aria-label={'View '+a.name}><ArrowUpRight size={20}/></button></div><p className="format-label">{a.format}</p></div></article>)}</div>
 {filtered.length===0&&<div className="empty-state"><Search size={32}/><h3>No assets found</h3><p>Try a different name or explore the full collection.</p><button className="button quiet" onClick={()=>{setQuery('');setCategory('All assets')}}>Reset filters</button></div>}
 <p className="demo-note">Illustrative creators, assets, and prices. Explore the demo without a wallet or payment.</p></section>
 <section id="how-it-works" className="how-section"><div className="how-intro"><p className="eyebrow">LESS FRICTION. MORE CREATION.</p><h2>From their spark.<br/>To your next thing.</h2><p>A simple exchange, with the important details upfront.</p></div><div className="steps"><div><span>01</span><section><h3>Find something worth building on.</h3><p>Explore previews, file details, and what’s included.</p></section><Box size={19}/></div><div><span>02</span><section><h3>Choose the right permission.</h3><p>Personal or commercial licenses for files. Time-bound passes for hosted tools.</p></section><FileText size={19}/></div><div><span>03</span><section><h3>Make it part of your work.</h3><p>Creators keep their rights. You get the agreed usage rights and a clear receipt.</p></section><Sparkles size={19}/></div></div></section>
 <section className="research-callout"><div><span className="research-icon"><Link2 size={30}/></span><div><p className="eyebrow">THE THINKING BEHIND SMARTSHARING</p><h2>A marketplace with a point of view.</h2><p>Four concepts. Real trade-offs. A practical role for Hedera.</p></div></div><a href="/research" className="button quiet">Read the research <ArrowUpRight size={18}/></a></section>
 <footer className="site-footer"><a className="brand" href="/"><Link2/>smartsharing<span>.in</span></a><span>Made to be shared.</span><a href="/research#sources">Sources & references <ArrowUpRight size={13}/></a><span className="footer-note">Interactive concept · No live transactions</span></footer>
 </main>
 <Sheet open={!!asset} onOpenChange={o=>{if(!o)setAsset(null)}}><SheetContent className="asset-sheet" aria-describedby="asset-description">{asset&&<><div className="sheet-image"><img src={asset.image} alt={asset.name}/><span className="concept-badge">ILLUSTRATIVE ASSET</span></div><div className="sheet-body"><p className="asset-category">{asset.category}</p><SheetTitle className="sheet-heading">{asset.name}</SheetTitle><SheetDescription id="asset-description" className="sheet-description">{asset.description}</SheetDescription><div className="creator-line"><span className={'avatar avatar-'+asset.id}>{asset.initials}</span><span>{asset.creator}<small>Illustrative creator · {asset.role}</small></span></div>
 {!receipt?<><Tabs defaultValue="license" className="asset-tabs"><TabsList className="w-full"><TabsTrigger value="license">Choose a license</TabsTrigger><TabsTrigger value="included">What’s included</TabsTrigger></TabsList><TabsContent value="license"><RadioGroup value={option} onValueChange={setOption} className="license-options" aria-label="License options">{licenseOptions(asset).map(o=><label key={o.id} className={'license-option '+(option===o.id?'chosen':'')}><RadioGroupItem value={o.id}/><span><strong>{o.name}</strong><small>{o.detail}</small></span><b>{money(o.price)}</b></label>)}</RadioGroup><p className="license-explainer">{asset.kind==='hosted'?'A hosted pass ends when its duration or run allowance is used up. Generated outputs remain with you, subject to the applicable model terms.':'Perpetual use under the chosen license. The creator retains ownership. Source files cannot be resold, redistributed, or sublicensed.'}</p></TabsContent><TabsContent value="included"><ul className="included-list">{asset.includes.map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul><p className="license-explainer">This is a product concept. The proposed files and hosted workflow are not supplied in this demo.</p></TabsContent></Tabs>
 <div className="checkout-breakdown"><div><span>Illustrative license price</span><b>{money(selection?.price??0)}</b></div><div><span>Creator receives (88%)</span><span>{money((selection?.price??0)*.88)}</span></div><div><span>Platform share (12%)</span><span>{money((selection?.price??0)*.12)}</span></div><p>Proposed split. Taxes and processing treatment require confirmation before launch.</p></div><label className="accept-license"><Checkbox checked={accepted} onCheckedChange={v=>setAccepted(v===true)}/><span>I understand this creates a sample receipt only. No payment, asset delivery, or legal license.</span></label><button className="button primary full" disabled={!accepted} onClick={simulate}>Try the license flow <ArrowRight size={17}/></button><p className="demo-note">No wallet needed · No funds moved</p></>:<div className="receipt-success"><CheckCircle2 size={43}/><h3>Your sample receipt is ready.</h3><p>The demo flow is complete. No money moved and no actual license was issued.</p><dl><div><dt>Reference</dt><dd>{receipt.id}</dd></div><div><dt>Permission</dt><dd>{receipt.license}</dd></div><div><dt>Illustrative total</dt><dd>{money(receipt.price)}</dd></div><div><dt>Ledger status</dt><dd>Demo only · not on-chain</dd></div></dl><button className="button primary full" onClick={()=>{setAsset(null);setCollection(true)}}>View my collection <ArrowRight size={17}/></button></div>}
 </div></>}</SheetContent></Sheet>
 <Dialog open={collection} onOpenChange={setCollection}><DialogContent className="collection-dialog"><DialogTitle className="dialog-heading">Your collection</DialogTitle><DialogDescription>Saved assets, sample receipts, and listing drafts from this session. Refreshing clears this demo.</DialogDescription><Tabs defaultValue="saved"><TabsList className="w-full"><TabsTrigger value="saved">Saved ({saved.length})</TabsTrigger><TabsTrigger value="receipts">Receipts ({receipts.length})</TabsTrigger><TabsTrigger value="drafts">Drafts ({drafts.length})</TabsTrigger></TabsList><TabsContent value="saved">{!saved.length?<div className="empty-state compact"><Bookmark size={26}/><h3>A little inspiration goes a long way.</h3><p>Save an asset using the bookmark on its card.</p></div>:assets.filter(x=>saved.includes(x.id)).map(a=><div className="collection-row" key={a.id}><img src={a.image} alt=""/><button onClick={()=>{setCollection(false);openAsset(a)}}><strong>{a.name}</strong><small>{a.category} · {money(a.price)}</small></button><button aria-label={'Remove '+a.name} onClick={()=>toggleSaved(a.id)}><X size={17}/></button></div>)}</TabsContent><TabsContent value="receipts">{!receipts.length?<div className="empty-state compact"><FileText size={26}/><h3>No sample receipts yet.</h3><p>Open an asset and try the license flow.</p></div>:receipts.map(r=><div className="receipt-row" key={r.id}><span className="receipt-icon"><FileText size={21}/></span><div><strong>{r.asset.name}</strong><small>{r.license} · {money(r.price)} · DEMO</small><code>{r.id}</code></div><CheckCircle2 size={19}/></div>)}</TabsContent><TabsContent value="drafts">{!drafts.length?<div className="empty-state compact"><PackageOpen size={28}/><h3>Have something to share?</h3><p>Try drafting your first asset listing.</p><button className="button quiet" onClick={()=>{setCollection(false);setListing(true);setDraftCreated(false)}}>Draft an asset <Plus size={16}/></button></div>:drafts.map(d=><div className="draft-row" key={d.id}><strong>{d.name}</strong><small>{d.category} · {money(d.price)} · Unpublished session draft</small><p>{d.description}</p></div>)}</TabsContent></Tabs></DialogContent></Dialog>
 <Dialog open={listing} onOpenChange={setListing}><DialogContent className="listing-dialog"><DialogTitle className="dialog-heading">{draftCreated?'Your idea has a starting point.':'Share something you made.'}</DialogTitle><DialogDescription>{draftCreated?'Your unpublished draft is in My collection for this session.':'Draft an asset listing. This demo does not upload files or publish to a marketplace.'}</DialogDescription>{draftCreated?<div className="draft-confirm"><CheckCircle2 size={40}/><p>Real listings will need asset uploads, rights review, verified delivery, and a payment connection.</p><button className="button primary full" onClick={()=>{setListing(false);setCollection(true)}}>View my collection <ArrowRight size={17}/></button></div>:<form className="listing-form" onSubmit={e=>{e.preventDefault();if(!rights)return;const f=new FormData(e.currentTarget);const name=String(f.get('name')??'').trim(),description=String(f.get('description')??'').trim(),price=Number(f.get('price'));if(!name||!description||!Number.isFinite(price)||price<99||price>100000)return;setDrafts(prev=>[{id:crypto.randomUUID(),name,description,price,category:draftCategory},...prev]);setDraftCreated(true);setRights(false)}}><label>Asset name<Input name="name" placeholder="e.g. My cinematic motion pack" required maxLength={70}/></label><label>Category<Select value={draftCategory} onValueChange={setDraftCategory}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{categories.slice(1).map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></label><label>What will someone be able to do with it?<Textarea name="description" placeholder="Describe what’s included and who it’s for." required maxLength={500}/></label><label>Starting price (INR)<Input name="price" type="number" min={99} max={100000} step={1} required defaultValue={499}/></label><label className="accept-license"><Checkbox checked={rights} onCheckedChange={v=>setRights(v===true)}/><span>I created this asset or have permission to license it.</span></label><button className="button primary full" type="submit" disabled={!rights}>Create session draft <Plus size={17}/></button></form>}</DialogContent></Dialog>
 </>
}
